### ISSUE TITLE
KeyError: predicateType not found in axis

### ISSUE THREAD

**Issue by dylan-knaggs** [socrata/autocensus#8]
When running the following query:
```
pop_vars = ['S0101_C01_001E']
start_year = 2010
table_type='subject'
    place_query = Query(
        estimate=estimate,
        years=range(start_year, end_year),
        variables=pop_vars,
        for_geo='place:46000,12000,27400,55000,73000,77000',
        in_geo=['state:04'],
        join_geography=False,
        table = table_type,
        census_api_key=key)
    places = place_query.run()
df_pop=getData(pop_vars,pop_start,end_year=end_year,estimate=estimate,
                   table_type='subject')
```
I get this error:
```
Traceback (most recent call last):
  File "census_vars.py", line 44, in <module>
    main()
  File "census_vars.py", line 30, in main
    df_1yr = census_init.getAllData(end_year=end_year,estimate=estimate)
  File "/Users/dylanknaggs/Desktop/cs_managed_jobs/City_of_Mesa_370871/census_init.py", line 350, in getAllData
    table_type='subject')
  File "/Users/dylanknaggs/Desktop/cs_managed_jobs/City_of_Mesa_370871/census_init.py", line 164, in getData
    places = place_query.run()
  File "/anaconda3/lib/python3.7/site-packages/autocensus/query.py", line 373, in run
    dataframe = self.assemble_dataframe(variables, tables, geography)
  File "/anaconda3/lib/python3.7/site-packages/autocensus/query.py", line 331, in assemble_dataframe
    variables_dataframe: DataFrame = self.convert_variables_to_dataframe(variables)
  File "/anaconda3/lib/python3.7/site-packages/autocensus/query.py", line 230, in convert_variables_to_dataframe
    columns=['attributes', 'group', 'limit', 'predicateType']
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 3940, in drop
    errors=errors)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 3780, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 3812, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 4965, in drop
    '{} not found in axis'.format(labels[mask]))
KeyError: "['predicateType'] not found in axis"
```

Its not clear to me where the predicateType variable is supposed to be generated (the only place in the autocensus code I can find it is in the line that sends an error). Note that this call was written on version 0.2.0, and runs on there, but fails on 1.0.5.

**Comment by cmsetzer** [comment]
Thanks for identifying this! There was a mistaken assumption that `predicateType` would always be included in the `/variables` output for a given table. In this case, no `predicateType` was included, thus the `KeyError`. I pushed up a fix in 14d12aa446277b29e8ef4615236923ea719ec9a9 and just released it in version 1.0.6. A `pip install --upgrade autocensus` should grab the latest version and resolve this.

Closing this issue out!
